SUPABASE_URL = "https://kuszuskblbjelv1lniggd.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3czVzemtibGJlanZsaW5pZ2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2MDAwMTUsImV4cCI6Mjg3NTI1NzQ1NX0.D9pt-rSNprcUrboLTgUEEn_qjFLuSX5boAVuVirknCE"
